services:
  mysql:
    build: ./mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=retail_db
    ports:
      - '3310:3306'
    volumes:
      - ./mysql/data:/mysql/data
  mongodb:
    build: ./mongodb/
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example